name: Scrape LinkedIn Username Selector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer@latest

      - name: Log Puppeteer Version
        run: |
          npm list puppeteer --depth=0 >> output.log 2>&1 || echo "Failed to log Puppeteer version" >> output.log
        continue-on-error: true

      - name: Scrape LinkedIn Profile
        id: scrape_step
        run: |
          # Ensure output.log is created even if empty
          touch output.log
          # Create a directory for screenshots
          mkdir -p screenshots
          node -e "
          const puppeteer = require('puppeteer');
          const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
          (async () => {
            const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox', '--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
            await page.setExtraHTTPHeaders({
              'Accept-Language': 'en-US,en;q=0.9',
              'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
            });
            try {
              await page.goto('https://www.linkedin.com/in/satyanadella', { waitUntil: 'domcontentloaded', timeout: 60000 });
              await delay(2000);

              // Take screenshot after initial load
              await page.screenshot({ path: 'screenshots/initial_load.png', fullPage: true });
              console.log('Initial load screenshot saved as screenshots/initial_load.png');

              // Log the page title for debugging
              const pageTitle = await page.title();
              console.log('Page title:', pageTitle);

              // Log a snippet of the HTML for debugging
              const pageContent = await page.evaluate(() => document.body.innerHTML.substring(0, 500));
              console.log('Page content snippet:', pageContent);

              // Check for and dismiss the sign-in modal
              const dismissButtonSelector = 'button[data-tracking-control-name=\"public_profile_contextual-sign-in-modal_modal_dismiss\"]';
              try {
                await page.waitForSelector(dismissButtonSelector, { timeout: 5000 });
                console.log('Dismiss button found, clicking...');
                await page.click(dismissButtonSelector);
                await delay(3000); // Wait longer for the profile page to load
                // Take screenshot after dismissing the modal
                await page.screenshot({ path: 'screenshots/after_dismiss.png', fullPage: true });
                console.log('After dismiss screenshot saved as screenshots/after_dismiss.png');
              } catch (error) {
                console.log('Dismiss button not found or click failed:', error.message);
              }

              // Log the page title again after dismissing the modal
              const pageTitleAfterDismiss = await page.title();
              console.log('Page title after dismiss:', pageTitleAfterDismiss);

              // Log a snippet of the HTML again for debugging
              const pageContentAfterDismiss = await page.evaluate(() => document.body.innerHTML.substring(0, 500));
              console.log('Page content snippet after dismiss:', pageContentAfterDismiss);

              // Scrape the name's CSS selector
              const selector = await page.evaluate(() => {
                // Find all h1 elements
                const h1Elements = Array.from(document.querySelectorAll('h1'));

                // Locate the h1 element containing "Satya Nadella"
                const nameElement = h1Elements.find(el => el.textContent?.trim() === 'Satya Nadella');

                if (!nameElement) {
                  console.log('Satya Nadella element not found.');
                  return 'Selector not found';
                }

                // Extract the dynamic class name (long alphanumeric class)
                const dynamicClass = nameElement.className
                  .split(' ')
                  .find(cls => cls.length > 20 && /^[a-zA-Z0-9]+$/.test(cls));

                if (!dynamicClass) {
                  console.log('Dynamic class not found on the Satya Nadella element.');
                  return 'No dynamic class found';
                }

                console.log('Dynamic class found:', dynamicClass);
                return `h1.${dynamicClass}`;
              });
              console.log('Latest selector:', selector);
              process.env.SELECTOR = selector;
            } catch (error) {
              console.log('Error:', error.message);
              process.env.SELECTOR = 'Failed to scrape - possible CAPTCHA or block: ' + error.message;
            }
            await browser.close();
          })();
          " >> output.log 2>&1
          # Extract selector and handle case where it might not be found
          SELECTOR_VALUE=$(cat output.log | grep 'Latest selector:' | sed 's/Latest selector: //')
          if [ -z "$SELECTOR_VALUE" ]; then
            echo "No selector found in output.log, checking for error"
            SELECTOR_VALUE=$(cat output.log | grep 'Error:' | sed 's/Error: //')
            if [ -z "$SELECTOR_VALUE" ]; then
              SELECTOR_VALUE="No data or error logged"
            fi
          fi
          # Sanitize SELECTOR_VALUE: remove spaces and special characters
          SANITIZED_SELECTOR=$(echo "$SELECTOR_VALUE" | tr -d '[:space:]' | sed 's/[^a-zA-Z0-9.-]/-/g')
          echo "SELECTOR=$SANITIZED_SELECTOR" >> $GITHUB_ENV
          echo "Debug: SELECTOR set to $SANITIZED_SELECTOR" >> output.log

      - name: Commit result
        run: |
          # Ensure files exist
          touch output.log
          touch result.txt
          # Commit screenshots if they exist
          if [ -d "screenshots" ]; then
            git add screenshots/*.png
          fi
          echo "$(date -u) - Selector: ${{ env.SELECTOR }}" >> result.txt
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add result.txt output.log
          git commit -m "Update selector and screenshots - $(date -u)" || echo "No changes to commit"
          git push

      - name: Post Set up Node.js
        run: echo "Node.js setup complete"

      - name: Post Checkout code
        run: echo "Checkout complete"

      - name: Complete job
        run: echo "Job completed"
